FROM node:alpine as build

WORKDIR /app/src

COPY /package.json .
COPY /package-lock.json .

RUN npm install

COPY . .

EXPOSE 8080

CMD ["npm","run","start"]



FROM nginx:stable-alpine

COPY --from=build /app/src/build /usr/share/nginx/html

RUN rm /etc/nginx/nginx.conf

COPY --from=build /app/src/nginx/nginx.conf /src/nginx/

EXPOSE 8080

CMD ["nginx","g","daemon off;"]

